import type { Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import Sidebar from "@/components/Sidebar";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Vira | Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={inter.variable}>
        <body className="font-sans antialiased"> 
          <SignedOut>
            <div className="flex justify-center items-center h-screen">
              <SignIn routing="hash" />
            </div>
          </SignedOut> 
          <SignedIn>
            <Providers>
            <div className="flex"> 
              <div className="w-64"> 
                 <Sidebar/>
              </div> 
              <main className="flex-1   p-4">{children}</main>
            </div>
            </Providers>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
