import type { Metadata } from "next";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Vira | Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={inter.variable}>
        <body className="font-sans antialiased">
          {/* When signed out, show SignIn */}
          <SignedOut>
            <div className="flex justify-center items-center h-screen">
              <SignIn routing="hash" />
            </div>
          </SignedOut>

          {/* When signed in, show Sidebar + page content */}
          <SignedIn>
            <div className="flex">
              {/* Sidebar stays fixed */}
              <div className="w-64">
                {/* Sidebar component here so it's shared across all pages */}
                {/* Lazy import inside SignedIn to avoid hydration mismatch */}
                 <Sidebar/>
              </div>
              {/* Page content here */}
              <main className="flex-1 ml-64 p-4">{children}</main>
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
